# Generated by Django 3.2 on 2021-07-22 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
